import Head from 'next/head'
import NavBar from '../components/navbar'
import CoverSection from '../components/cover-section'
import Collections from '../components/collections'
import Collectibles from '../components/collectibles'

const collections = [
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    price: '$500',
    volume: '$24,000,000',
  },
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    price: '$500',
    volume: '$24,000,000',
  },
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    price: '$500',
    volume: '$24,000,000',
  },
]

export const collectibles = [
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    time: '2d 1h 23m 1s',
    mintAmount: '100,000',
    by: 'Young Thug'
  },
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    time: '2d 1h 23m 1s',
    mintAmount: '100,000',
    by: 'Young Thug'
  },
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    time: '2d 1h 23m 1s',
    mintAmount: '100,000',
    by: 'Young Thug'
  },
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    time: '2d 1h 23m 1s',
    mintAmount: '100,000',
    by: 'Young Thug'
  },
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    time: '2d 1h 23m 1s',
    mintAmount: '100,000',
    by: 'Young Thug'
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <CoverSection
        imageName='cover1'
        heading='Collectibles'
        description='Verified NFT marketplace for music artists.'
      />
      <Collections
        heading='Top Collections'
        viewAll='#'
        collections={collections}
      />
      <Collectibles
        heading='Collectibles'
        viewAll='#'
        collections={collectibles}
      />
    </>
  )
}
