import Head from 'next/head'
import NavBar from '../components/navbar'
import CoverSection from '../components/cover-section'
import Collections from '../components/collections'

const collections = [
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    price: '$500',
    volume: '$24,000,000',
  },
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    price: '$500',
    volume: '$24,000,000',
  },
  {
    imageUrl: 'https://bit.ly/sage-adebayo',
    name: 'Music Heroes',
    price: '$500',
    volume: '$24,000,000',
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <CoverSection
        imageName='cover1'
        heading='Collectibles'
        description='Verified NFT marketplace for music artists.'
      />
      <Collections
        heading='Top Collections'
        viewAll='#'
        collections={collections}
      />
    </>
  )
}
